Library/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class FormController : Controller
    {
        public ActionResult Form()
        {
            return View("FormPage", HttpContext.Application["forms"]);
        }

        [HttpPost]
        public ActionResult FormPage(string name, string genre, 
            bool wantScifi, bool wantMobileVersion)
        {
            (HttpContext.Application["forms"] as List<(string, string, bool, bool)>)
                .Add((name, genre, wantScifi, wantMobileVersion));
            return RedirectToAction("FormPage");
        }

        [HttpGet]
        public ActionResult FormPage()
        {
            return View("FormPageResult", HttpContext.Application["forms"]);
        }
    }
}

Library/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class GuestController : Controller
    {
        // GET: Guest
        public ActionResult GuestPage()
        {
            return View(HttpContext.Application["reviews"]);
        }

        [HttpPost]
        public ActionResult AddReview(string name, string date, string text)
        {
            (HttpContext.Application["reviews"] as List<(string, string, string)>)
                .Add((name, date, text));
            return new RedirectResult("/Guest/GuestPage");
        }
    }
}

Library/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class MainController : Controller
    {
        public ActionResult MainPage()
        {
            return View(HttpContext.Application["articles"]);
        }
    }
}

Library/Views/Form/FormPage.cshtml
@{
    ViewBag.Title = "Form Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>

<div id="form">

    @using (Html.BeginForm("FormPage", "Form", FormMethod.Post))
    {
        <label>Enter your name</label>
        @Html.TextBox("name", "");
<p>
    Do you want more science fiction books?
    <span>
        @Html.CheckBox("wantSciFi")
    </span>
</p>
<p>
    Do you want a version of this site for smartphones?
    <span>
        @Html.CheckBox("wantMobileVersion", "")
    </span>
</p>
        <ul>What literary genre do you prefer?</ul><br />
        <li>Utopian fiction @Html.RadioButton("genre", "Utopian fiction")</li><br />
        <li>Historical fiction @Html.RadioButton("genre", "Historical fiction")</li><br />
        <li>Crime novel @Html.RadioButton("genre", "Crime novel")</li><br />
        <li>Adventure @Html.RadioButton("genre", "Adventure")</li><br /><br />
        <input class="submit" type="submit" value="Send" />
    }
</div>
<script scr="~/Scripts/FormResult.js"></script>

Library/Views/Form/FormPageResult.cshtml
@{
    ViewBag.Title = "FormPageRes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@MyHelpers.DrawResultsOfForms(Model)

Library/Views/Guest/GuestPage.cshtml
@{
    ViewBag.Title = "Guest Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

<div id="reviews">
    @foreach ((string name, string dateOfPublish, string text) a in Model)
    {
        <div class="article">
            <p>@a.name:</p>
            <p>@a.dateOfPublish</p>
            <p>@a.text</p>
        </div>
    }

    @using (Html.BeginForm("AddReview", "Guest", FormMethod.Post))
    {
        <input type="hidden" value=@DateTime.Now.ToShortDateString() name="date" />
        <p>Enter your name</p>
        @Html.TextBox("name", "");
        <p>Enter your review</p>
        @Html.TextArea("text", "", null);
        <input class="submit" type="submit" value="Send" />
    }
</div>

Library/Views/Main/MainPage.cshtml
@{
    ViewBag.Title = "Main Page";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@foreach((string name, string dateOfPublish, string text) a in Model)
{
        <h2>@a.name</h2>
        <p>@a.dateOfPublish</p>
        <br />
        <p>@a.text</p>
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <main>
        <h1>
            <span id="title">
                <img alt="logo" src="~/logo.png" class="logo" />
            </span>Library "Task23_Low"
        </h1>
    </main>
    <div id="content">
        <div id="left">
            @RenderBody()
        </div>
        <div id="menu">
            <nav id="links">
                <a href="/Main/MainPage">Main page</a>
                <a href="/Guest/GuestPage">Guest page</a>
                <a href="/Form/Form">Form page</a>
            </nav>
        </div>
    </div>
    <br />
    <footer>
        <p>
            <span>
                Copyright &copy; @DateTime.Now.Year. All Rights Reserved.
            </span>
            Maksym Kot 
            <span>
                <a href="mailto:rabbit0165@gmail.com">rabbit0165@gmail.com</a>
            </span>
            <span><a href="#" id="up">To Top</a></span>
        </p>
        <script src="~/Scripts/up.js"></script>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>